### ISSUE TITLE
Adidas Nz

### ISSUE THREAD

**Issue by speshalforces** [aklingspor/yeezycopper-beta#1]
hey man i was just wondering if you could change the code or point me in the direction to getting this to work on the adidas new zealand site, i have changed the json file to read adidas.co.nz but when the extension is running it stops before the cc info, i was thinking maybe it could have something to do with the address lines being different etc. but other than that it runs fine for the add to cart.
Thanks in advance

**Comment by aklingspor** [comment]
Sorry, an entire separate bot would have to be made just for the NZ website, because the code design of the NZ website differs. In the future, I will plan to develop bots for major international adidas branch websites
