### ISSUE TITLE
// YEEZY COPPER HELP // HOW CAN I MAKE IT SO IT WORKS ON RUSSIAN ADIDAS NOT THE US ONE? PLZ HELP

### ISSUE THREAD

**Issue by Lourex** [aklingspor/yeezycopper-beta#3]

**Comment by aklingspor** [comment]
Thanks for your inquiry, seems like you closed the topic. International bot releases may be coming soon. Please open a new topic if anything else pops up.

**Comment by Lourex** [comment]
is it hard to rewrite a code a bit? I do code, but i think it's to hard for
me.
I dont know which element is which. New yeezys coming out, so i really want
to cop them with this free bot.

2016-12-13 21:02 GMT+03:00 Antonio Klingspor <notifications@github.com>:

**Comment by aklingspor** [comment]
I'll try to rewrite it tonight for you.

Anton

**Comment by Lourex** [comment]
Thx a lot man!

2016-12-13 21:51 GMT+03:00 Antonio Klingspor <notifications@github.com>:

> I'll try to rewrite it tonight for you.
>
> Anton

**Comment by Lourex** [comment]
?

**Comment by aklingspor** [comment]
I am completely swamped with requests for over 20+ countries. One man team.
Please
Be patient

**Comment by Lourex** [comment]
Ok, tomorrow new yeezys are being dropped, that's the problem 

Отправлено с iPhone

> 16 дек. 2016 г., в 16:44, Antonio Klingspor <notifications@github.com> написал(а):
> 
> I am completely swamped with requests for over 20+ countries. One man team.
> Please
> Be patient

**Comment by aklingspor** [comment]
I know, but please release I'm offering this completely free

**Comment by julper** [comment]
Hi @aklingspor ! 
I am also interested if you can rewrite it for the french website :)
Have a nice day !
